### ISSUE TITLE
Error compiling web server

### ISSUE THREAD

**Issue by kwcne** [TETYYS/SAPI4#2]
Running into the following error when I try to compile the web server.
```
sapi4 ~master: building configuration "application"...
Compiling Diet HTML template index.dt...
source/app.d(16,2): Error: variable `app.SAM.this.conn` has scoped destruction, cannot build closure
/usr/bin/dmd failed with exit code 1.
```

**Comment by ohsshoot** [comment]
Issue is in the one of the constructors (I think it's a constructor? I have a rudimentary knowledge of D), near the top of app.d. I can't remember what exactly I changed since I fixed it at least a month ago, but my final constructor looks like this:

`	this(string voice, ushort defPitch, ushort minPitch, ushort maxPitch, uint defSpeed, uint minSpeed, uint maxSpeed, TCPConnection con) {
		this.con = con;
		this.voice = voice;
		this.defPitch = defPitch;
		this.minPitch = minPitch;
		this.maxPitch = maxPitch;
		this.defSpeed = defSpeed;
		this.minSpeed = minSpeed;
		this.maxSpeed = maxSpeed;
		this.pingTask = runTask({
			for (;;) {
				this.con.write([ cast(ubyte)0, cast(ubyte)0 ]);
				ubyte[2] p;
				this.con.read(p);
				sleep(60.seconds);
			}
		});
	}
}
`

**Comment by 258528** [comment]
CAN THE WEBSITE PLEASE BACK UP ALREADY?!

**Comment by TETYYS** [comment]
stfu muttonhead

**Comment by TETYYS** [comment]
i have changed all of the code so this is probably not relevant anymore
